FoodDay/urls.py
from Cart.views import get_cart_widget, update_cart, add_to_cart
from django.conf import settings
from django.conf.urls import patterns, include, url
from Order.views import handle_order_form, show_orders, timeslots

from Products.views import ProductDetailView, ProductIndexView, ProductCategoryIndexView, \
    ProducerIndexView, ProducerDetailView, product_category, get_product_sidebar_rendered
from Misc.views import FrontPageView, BasePageView, AboutPageView, FooterPageView, FaqPageView
from Recipes.views import RecipeDetailView, get_recipe_sidebar_rendered, recipe_category, buy_recipe_modal

# Uncomment the next two lines to enable the admin:
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()


urlpatterns = patterns('',

    # MISC
    url(r'^$', BasePageView.as_view(), name='basepage'),
    url(r'^frontpage/', FrontPageView.as_view(), name='frontpage'),
    url(r'^about/', AboutPageView.as_view(), name='about'),
    url(r'^footer/', FooterPageView.as_view(), name='footer'),
    url(r'^faq/', FaqPageView.as_view(), name='faq'),

    # PRODUCT
    url(r'^product/$', ProductIndexView.as_view(), name='product_list'),
    url(r'^product/(?P<pk>\d+)/$', ProductDetailView.as_view(), name='product_detail'),

    # CART
    url(r'^cart/widget/$', get_cart_widget, name='cart_widget'),
    url(r'cart/add/$', add_to_cart, name='cart_add'),
    url(r'cart/update/$', update_cart, name='cart_update'),

    # PRODUCER
    url(r'^producer/$', ProducerIndexView.as_view(), name='producer_list'),
    url(r'^producer/(?P<pk>\d+)/$', ProducerDetailView.as_view(), name='producer_detail'),

    # PRODUCT_CATEGORY
    url(r'^product-category/$', ProductCategoryIndexView.as_view(), name='product_category_list'),
    url(r'^product-category/(?P<pk>\d+)/$', product_category, name='product_category_detail'),
    url(r'^product-category-sidebar/$', get_product_sidebar_rendered, name='product_category_sidebar'),
    #url(r'^product-category/(?P<pk>\d+)/$', ProductCategoryDetailView.as_view(), name='product_category_detail'),

    # RECIPE
    url(r'^recipe/(?P<pk>\d+)/$', RecipeDetailView.as_view(), name='recipe_detail'),
    url(r'^buy-recipe-modal/(?P<pk>\d+)/(?P<servings>\d+)/$', buy_recipe_modal, name='buy_recipe_modal'),

    # RECIPE_CATEGORY
    url(r'^recipe-category-sidebar/$', get_recipe_sidebar_rendered, name='recipe_category_sidebar'),
    url(r'^recipe-category/(?P<pk>\d+)/$', recipe_category, name='recipe_category_detail'),

    url(r'^order/$', handle_order_form, name='handle_order_form'),
    url(r'^order/timeslots/(?P<skip>\d+)$', timeslots, name='timeslots'),
    url(r'^orders/supersecret/$', show_orders, name='show_orders'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Products/models.py
# coding=UTF-8
from django.db import models
from IngredientProductMapping.models import QuantityType


class Product(models.Model):

    #Fields
    name = models.CharField(max_length=150)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(verbose_name='height 400px, width 326px', upload_to='product_images',
                              default='product_images/product_images_placeholder.png', blank=True)
    stk = models.IntegerField(blank=True, null=True, verbose_name='Hvor mange stk. er '
                                                                  'denne varen? (La feltet '
                                                                  'være tomt hvis dette er irrevelevant '
                                                                  'for denne varen.)')

    #Relations
    quantityType = models.ForeignKey(QuantityType)
    producer = models.ForeignKey('Producer')
    productCategories = models.ManyToManyField('ProductCategory', blank=True, null=True, related_name='products')
    ingredientMapping = models.ForeignKey('IngredientProductMapping.IngredientProductMapping', related_name='products', blank=True, null=True)

    def __unicode__(self):
        return self.name + ' kr.' + str(self.price)

    def _price_per_mass(self):
        """ Returns a tuple with (price/weight, unit) """
        mass, unit = self.quantityType.get_normalized_mass_unit(self.quantity)
        return self.price/mass, unit

    def pretty_price_per_mass(self):
        """ Returns a string for displaying price per weight unit """
        price_mass, unit = self._price_per_mass()
        return u'{:.2f} kr/{unit}'.format(price_mass, unit=unit)

    def pretty_price(self):
        return u'{price},-'.format(price=self.price)

    def get_price(self):
        return self.price


class Producer(models.Model):
    name = models.CharField(max_length=150)

    def __unicode__(self):
        return self.name


class ProductCategory(models.Model):
    name = models.CharField(max_length=150)
    parents = models.ManyToManyField('self', blank=True, null=True, symmetrical=False, related_name='children')

    def __unicode__(self):
        return self.name

Products/views.py
# Create your views here.
from django.shortcuts import render_to_response
from django.template import Context
from django.template.loader import get_template
from django.views import generic
from Products.models import Product, ProductCategory, Producer


class ProductIndexView(generic.ListView):
    template_name = 'product_index.html'
    context_object_name = "product_list"

    def get_queryset(self):
        return Product.objects.order_by('pk')


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'product_detail.html'


class ProducerIndexView(generic.ListView):
    template_name = 'producer_index.html'
    context_object_name = "producer_list"

    def get_queryset(self):
        return Producer.objects.order_by('name')


class ProducerDetailView(generic.DetailView):
    model = Producer
    template_name = 'producer_detail.html'


class ProductCategoryIndexView(generic.ListView):
    template_name = 'product_category_index.html'
    context_object_name = 'product_category_list'

    def get_queryset(self):
        return ProductCategory.objects.order_by('name')


class ProductCategoryDetailView(generic.DetailView):
    model = ProductCategory
    template_name = 'product_category_detail.html'


def get_product_sidebar_rendered(request):
    product_category_list = ProductCategory.objects.filter(parents=None).all()
    return render_to_response('product_category_sidebar.html', {'product_category_list': product_category_list})


def product_category(request, **kwargs):
    productcategory = ProductCategory.objects.get(pk=kwargs['pk'])
    return render_to_response('product_category_detail.html', {'productcategory' : productcategory})

Products/templates/producer_detail.html
{% extends 'base.html' %}
{% block content %}
    <h2> {{ producer.name }}</h2>
    <ul>
        {% for product in producer.product_set.all %}
            <li><a href="{% url 'product_detail' product.id %}"> {{ product.name }} </a></li>
        {% endfor %}
    </ul>
{% endblock %}

Products/templates/producer_index.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <ul>
    {% for producer in producer_list %}
        <li><a href="{% url 'producer_detail' producer.id %}"> {{ producer.name }} </a></li>
    {% endfor %}
    </ul>
</body>
</html>

Products/templates/product_category_detail.html
<h3> {{ productcategory.name }}</h3>
<div class="row">
    {% for product in productcategory.products.all %}
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <a class="product-link" data-product_id="{{ product.id }}" href="#" onclick="return false;">
            <div class="panel panel-success productpanel" data-product_id="{{ product.id }}">
                    <div class="panel-heading">
                        {{ product.name }}
                    </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-6 col-md-6 col-lg-6">
                            <img src="{{ product.image.url }}" id="productimg{{ product.id }}" class="img-responsive center-block product-img"/>
                        </div>
                        <div class="col-xs-6 col-md-6 col-lg-6">
                            <h7>{{ product.producer.name }}</h7>
                            <h6>{{ product.pretty_price }}</h6>
                            <h6>{{ product.quantity }} {{ product.quantityType }}</h6>
                            <h6>{{ product.pretty_price_per_mass }}</h6>
                            <button type="button" data-product_id="{{ product.id }}" class="btn btn-success btn-lg buy-product-btn">Kjøp</button>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</div>

Products/templates/product_category_index.html
{% extends 'base.html' %}
{% block content %}
    <ul>
        {% for product_category in product_category_list %}
            <li><a href="{% url 'product_category_detail' product_category.id %}"> {{ product_category.name }} </a> </li>
        {% endfor %}
    </ul>
{% endblock content %}

Products/templates/product_category_sidebar.html
<h3 class="text-center">Dagligvarer</h3>
<div class="panel-group" id="sidebar">
    {% for product_category in product_category_list %}
    <div class="panel-success">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a class="sidebar-toggle" data-toggle="collapse" data-parent="#sidebar" href="#collapse{{ product_category.id }}">
                    {{ product_category.name }}
                </a>
            </h4>
        </div>
        <div id="collapse{{ product_category.id }}" class="panel-collapse collapse">
            <div class="panel-body">
                <ul class="sidebar-list">
                    {% for product_subcategory in product_category.children.all %}
                        <li>
                            <div class="sidebar-subcat" data-product_cat_id="{{ product_subcategory.id }}">
                                <a class="sidebar-link" href="#/product-category/{{ product_subcategory.id }}">{{ product_subcategory.name }}</a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

Products/templates/product_detail.html
<h3 class="text-center">{{ product.name }} {{ product.mass }}{{ product.massUnit }}</h3>


<div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
        <img height="326" width="100" id="productimg{{ product.id }}" src="{{ product.image.url }}" class="img-responsive center-block"/>
    </div>
</div>

<div class="row">
    <div class="col-xs-9 col-sm-offset-3 col-sm-6 col-md-offset-4 col-md-4 col-lg-offset-4 col-lg-4">
        <h4 class="text-right">fra {{ product.producer }}</h4>
    </div>
</div>

<div class="row">
    <div class="col-xs-6 col-sm-offset-4 col-sm-2 col-md-offset-4 col-md-2 col-lg-offset-4 col-lg-2 text-right">
            <h3>{{ product.pretty_price }}</h3>
            <h6>{{ product.pretty_price_per_mass }}</h6>
    </div>
    <div class="col-xs-4 col-sm-2 col-md-2 col-lg-2">
            <button type="button" data-product_id="{{ product.id }}" class="btn btn-success btn-lg custom-btn-big buy-product-btn">Kjøp</button>
    </div>
</div>

<div class="row big-top-margins">
    <div class="col-xs-12 col-sm-12 col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-8">
        <div class="panel panel-default">
            <div class="panel-body">
                <p>{{ product.description | safe }}</p>
            </div>
        </div>
    </div>
</div>

<input type="hidden" name="id" value="{{ product.id }}" />
<input type="hidden" name="csrftoken" value="{% csrf_token %}" />

Products/templates/product_index.html
{% extends 'base.html' %}

{% block content %}
    <ul>
    {% for product in product_list %}
        <li><a href="{% url 'product_detail' product.id %}"> {{ product.name }} </a></li>
    {% endfor %}
    </ul>
{% endblock %}